name: Update coverage comment
on:
  pull_request:
    types: [edited]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test and report
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          workflow_conclusion: success
          commit: ${{github.event.pull_request.base.sha}}
          name: 'test-coverage-output'
          path: artifacts
          search_artifacts: 'test-coverage-output'

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'artifacts/coverage-summary.json'

      - name: File exists
        uses: ./
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        with:
          coverage_output_directory: 'artifacts/test-coverage-output/'
