on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test and report
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1000

      - name: Fetch base
        run: git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1000

      - name: Run tests
        run: |
          npm i
          npm run test

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: Test coverage output
          path: coverage

      - name: Download coverage artifact
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Report coverage
        uses: ./
        with:
          coverage_output_directory: 'artifacts/coverage'
