on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test and report
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1000

      - name: Fetch base
        run: git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1000

      - name: Run tests
        run: |
          npm i
          npm run test

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage-output
          path: coverage

      - name: Download coverage artifact
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          workflow: 'main.yml'
          workflow_conclusion: success
          commit: ${{github.event.pull_request.base.sha}}
          name: 'test-coverage-output'
          path: base-artifacts
          search_artifacts: 'test-coverage-output'

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'base-artifacts/coverage-summary.json'

      - name: Report coverage
        uses: ./
        id: report
        with:
          coverage_output_directory: 'artifacts/test-coverage-output/'
          base_coverage_output_directory: ${{steps.check_files.outputs.files_exists == 'true' && 'base-artifacts/' || ''}}

      - name: Generate comment content
        run: npx svelte-to-html comment-template.svelte comment.html '{"json":"${{toJSON(steps.report.outputs)}}"}'

      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: 'comment.html'

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- report-nyc-coverage-github-action-comment-mark -->'

      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.read_file.outputs.contents }}

      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: ${{ steps.read_file.outputs.contents }}
